### ISSUE TITLE
word weighting

### ISSUE THREAD

**Issue by johko** [grammatical/magec-wnut2019#2]
Hi,
I'm just in the process of training my own German model with your project. I managed to create most files needed, but I wondered how you do the word-weighting for the w2 file. What exactly is the process behind that?

**Comment by snukky** [comment]
I added the script for this there: https://github.com/grammatical/magec-wnut2019/blob/master/training/tools/edit_weights.py
For formal description, please see Section 3.5 in https://www.aclweb.org/anthology/N18-1055.pdf

**Comment by johko** [comment]
Nice, thank you!

**Comment by johko** [comment]
I ran into another problem concerning the word weighting. After creating the weights with the tokenized text (from spacy) I run into the problem that the number of tokens created by sentencepiece during training differs from the spacy tokens.
This way, the number of weights fed to Marian is wrong as well.

Is there a "simple" way around it or should I tokenize with sentencepiece and then create weights from that?

**Comment by snukky** [comment]
Yes, weights need to be generated from subword-segmented texts. For SentencePiece-based vocabs, the text needs be segmented outside Marian using:
```
./marian/build/spm_encode --model vocab.spm < text.in > text.segmented.out
```

**Comment by johko** [comment]
Thanks for the quick answer. That worked out. 
Only thing was that I had to add "--output" in front of the sentencepiece output file, else it would always write to the std out.
