### ISSUE TITLE
Handling of Special Characters

### ISSUE THREAD

**Issue by johko** [grammatical/magec-wnut2019#3]
Hi,

I've noticed that the performance of your german model isn't that good when it comes to special characters such as & or * in text. (I haven't tested the other languages)
I've also finetuned the model with own examples (about 300 000 lines) that also include samples with special characters. Still the transformer was not really able to handle them. In most cases the special character just gets turned into a letter or word. Sometimes it gets a bit crazier and the transformer creates some random long sequence of letters or word repetitions out of the special characters.

Is that a behaviour you have observed as well and do you think it can be solved by more examples? 
I know that might be hard to answer with certainty, but I just wanted to know your opinion about it.

**Comment by snukky** [comment]
I think it's a problem with vocabulary. Those characters didn't have enough coverage when training the vocab and internally they are replaced with unks. A solution would be retraining a model with better vocab.

**Comment by johko** [comment]
Thanks for the quick answer, I'll try it.
